/**
 * Niche Research Department - Seeded Country Potential Database
 * 50+ countries with research-calibrated internet metrics, RPM ranges, and monetization potentials.
 * Serves as the bedrock for the Country Potential Intelligence Agent.
 */

import type { CountryRecord } from '../types';

export const SEEDED_COUNTRIES: Omit<CountryRecord, 'createdAt' | 'updatedAt'>[] = [
  // --- TIER 1 MARKETS (Maximum RPM, Elite Affiliate Networks, High Purchasing Power) ---
  {
    countryCode: 'US',
    name: 'United States',
    flag: '🇺🇸',
    internetUsers: 312000000,
    ecommerceSpendUSD: 1137000000000,
    rpmRangeLow: 28.0,
    rpmRangeHigh: 85.0,
    affiliateStrength: 10.0,
    languageFit: 'English (Native/Primary)',
    potentialScore: 98.5,
    tier: 'tier1'
  },
  {
    countryCode: 'UK',
    name: 'United Kingdom',
    flag: '🇬🇧',
    internetUsers: 66000000,
    ecommerceSpendUSD: 245000000000,
    rpmRangeLow: 22.0,
    rpmRangeHigh: 65.0,
    affiliateStrength: 9.6,
    languageFit: 'English (Native/Primary)',
    potentialScore: 95.0,
    tier: 'tier1'
  },
  {
    countryCode: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    internetUsers: 36500000,
    ecommerceSpendUSD: 98000000000,
    rpmRangeLow: 20.0,
    rpmRangeHigh: 60.0,
    affiliateStrength: 9.3,
    languageFit: 'English / French Bilingual',
    potentialScore: 93.5,
    tier: 'tier1'
  },
  {
    countryCode: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    internetUsers: 24500000,
    ecommerceSpendUSD: 65000000000,
    rpmRangeLow: 24.0,
    rpmRangeHigh: 68.0,
    affiliateStrength: 9.4,
    languageFit: 'English (Native/Primary)',
    potentialScore: 94.0,
    tier: 'tier1'
  },
  {
    countryCode: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    internetUsers: 78000000,
    ecommerceSpendUSD: 125000000000,
    rpmRangeLow: 18.0,
    rpmRangeHigh: 52.0,
    affiliateStrength: 8.9,
    languageFit: 'German (Native) / High English',
    potentialScore: 91.0,
    tier: 'tier1'
  },
  {
    countryCode: 'AE',
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    internetUsers: 9900000,
    ecommerceSpendUSD: 14000000000,
    rpmRangeLow: 16.0,
    rpmRangeHigh: 48.0,
    affiliateStrength: 8.5,
    languageFit: 'Arabic / High English Commercial',
    potentialScore: 89.0,
    tier: 'tier1'
  },
  {
    countryCode: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    internetUsers: 5600000,
    ecommerceSpendUSD: 11000000000,
    rpmRangeLow: 19.0,
    rpmRangeHigh: 54.0,
    affiliateStrength: 8.8,
    languageFit: 'English (Business Primary)',
    potentialScore: 90.5,
    tier: 'tier1'
  },
  {
    countryCode: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    internetUsers: 16800000,
    ecommerceSpendUSD: 36000000000,
    rpmRangeLow: 17.0,
    rpmRangeHigh: 50.0,
    affiliateStrength: 8.7,
    languageFit: 'Dutch / Near-Native English',
    potentialScore: 89.5,
    tier: 'tier1'
  },
  {
    countryCode: 'FR',
    name: 'France',
    flag: '🇫🇷',
    internetUsers: 60500000,
    ecommerceSpendUSD: 155000000000,
    rpmRangeLow: 15.0,
    rpmRangeHigh: 45.0,
    affiliateStrength: 8.4,
    languageFit: 'French (Native Required)',
    potentialScore: 87.0,
    tier: 'tier1'
  },
  {
    countryCode: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    internetUsers: 9900000,
    ecommerceSpendUSD: 21000000000,
    rpmRangeLow: 18.0,
    rpmRangeHigh: 52.0,
    affiliateStrength: 8.8,
    languageFit: 'Swedish / Fluent English',
    potentialScore: 88.5,
    tier: 'tier1'
  },
  {
    countryCode: 'NO',
    name: 'Norway',
    flag: '🇳🇴',
    internetUsers: 5300000,
    ecommerceSpendUSD: 17000000000,
    rpmRangeLow: 20.0,
    rpmRangeHigh: 58.0,
    affiliateStrength: 8.6,
    languageFit: 'Norwegian / Fluent English',
    potentialScore: 89.0,
    tier: 'tier1'
  },
  {
    countryCode: 'DK',
    name: 'Denmark',
    flag: '🇩🇰',
    internetUsers: 5800000,
    ecommerceSpendUSD: 19000000000,
    rpmRangeLow: 18.0,
    rpmRangeHigh: 50.0,
    affiliateStrength: 8.5,
    languageFit: 'Danish / Fluent English',
    potentialScore: 88.0,
    tier: 'tier1'
  },
  {
    countryCode: 'FI',
    name: 'Finland',
    flag: '🇫🇮',
    internetUsers: 5400000,
    ecommerceSpendUSD: 12000000000,
    rpmRangeLow: 16.0,
    rpmRangeHigh: 46.0,
    affiliateStrength: 8.2,
    languageFit: 'Finnish / Fluent English',
    potentialScore: 86.5,
    tier: 'tier1'
  },
  {
    countryCode: 'IE',
    name: 'Ireland',
    flag: '🇮🇪',
    internetUsers: 4900000,
    ecommerceSpendUSD: 13000000000,
    rpmRangeLow: 19.0,
    rpmRangeHigh: 55.0,
    affiliateStrength: 8.7,
    languageFit: 'English (Native)',
    potentialScore: 89.0,
    tier: 'tier1'
  },
  {
    countryCode: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    internetUsers: 4700000,
    ecommerceSpendUSD: 9500000000,
    rpmRangeLow: 18.0,
    rpmRangeHigh: 52.0,
    affiliateStrength: 8.6,
    languageFit: 'English (Native)',
    potentialScore: 88.0,
    tier: 'tier1'
  },
  {
    countryCode: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    internetUsers: 8400000,
    ecommerceSpendUSD: 23000000000,
    rpmRangeLow: 22.0,
    rpmRangeHigh: 65.0,
    affiliateStrength: 8.9,
    languageFit: 'German / French / Italian / English',
    potentialScore: 92.0,
    tier: 'tier1'
  },
  {
    countryCode: 'AT',
    name: 'Austria',
    flag: '🇦🇹',
    internetUsers: 8200000,
    ecommerceSpendUSD: 14000000000,
    rpmRangeLow: 16.0,
    rpmRangeHigh: 48.0,
    affiliateStrength: 8.3,
    languageFit: 'German (Native)',
    potentialScore: 86.0,
    tier: 'tier1'
  },
  {
    countryCode: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    internetUsers: 10900000,
    ecommerceSpendUSD: 18000000000,
    rpmRangeLow: 15.0,
    rpmRangeHigh: 45.0,
    affiliateStrength: 8.3,
    languageFit: 'Dutch / French / English',
    potentialScore: 85.5,
    tier: 'tier1'
  },

  // --- HIGH-POTENTIAL MARKETS (Rapid Growth, Lower SERP Resistance, High Scaling Leverage) ---
  {
    countryCode: 'SA',
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    internetUsers: 35000000,
    ecommerceSpendUSD: 22000000000,
    rpmRangeLow: 12.0,
    rpmRangeHigh: 38.0,
    affiliateStrength: 7.9,
    languageFit: 'Arabic (Primary) / English',
    potentialScore: 84.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'MY',
    name: 'Malaysia',
    flag: '🇲🇾',
    internetUsers: 31000000,
    ecommerceSpendUSD: 13000000000,
    rpmRangeLow: 7.0,
    rpmRangeHigh: 22.0,
    affiliateStrength: 7.8,
    languageFit: 'Malay / High English Commercial',
    potentialScore: 81.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'ID',
    name: 'Indonesia',
    flag: '🇮🇩',
    internetUsers: 212000000,
    ecommerceSpendUSD: 62000000000,
    rpmRangeLow: 4.5,
    rpmRangeHigh: 15.0,
    affiliateStrength: 7.5,
    languageFit: 'Indonesian (Bahasa)',
    potentialScore: 83.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    internetUsers: 51000000,
    ecommerceSpendUSD: 54000000000,
    rpmRangeLow: 11.0,
    rpmRangeHigh: 32.0,
    affiliateStrength: 7.6,
    languageFit: 'Italian (Native Required)',
    potentialScore: 80.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    internetUsers: 43000000,
    ecommerceSpendUSD: 46000000000,
    rpmRangeLow: 10.0,
    rpmRangeHigh: 30.0,
    affiliateStrength: 7.8,
    languageFit: 'Spanish (Native Global Reach)',
    potentialScore: 82.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    internetUsers: 102000000,
    ecommerceSpendUSD: 180000000000,
    rpmRangeLow: 14.0,
    rpmRangeHigh: 40.0,
    affiliateStrength: 8.5,
    languageFit: 'Japanese (Strict Localization)',
    potentialScore: 86.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'KR',
    name: 'South Korea',
    flag: '🇰🇷',
    internetUsers: 50000000,
    ecommerceSpendUSD: 140000000000,
    rpmRangeLow: 12.0,
    rpmRangeHigh: 35.0,
    affiliateStrength: 8.1,
    languageFit: 'Korean (Strict Localization)',
    potentialScore: 83.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    internetUsers: 165000000,
    ecommerceSpendUSD: 41000000000,
    rpmRangeLow: 5.0,
    rpmRangeHigh: 18.0,
    affiliateStrength: 7.9,
    languageFit: 'Portuguese (Brazilian)',
    potentialScore: 81.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    internetUsers: 98000000,
    ecommerceSpendUSD: 33000000000,
    rpmRangeLow: 6.0,
    rpmRangeHigh: 20.0,
    affiliateStrength: 7.7,
    languageFit: 'Spanish (Latin America Hub)',
    potentialScore: 80.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    internetUsers: 43000000,
    ecommerceSpendUSD: 9000000000,
    rpmRangeLow: 8.0,
    rpmRangeHigh: 25.0,
    affiliateStrength: 7.4,
    languageFit: 'English (Primary Commercial)',
    potentialScore: 78.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'TR',
    name: 'Turkey',
    flag: '🇹🇷',
    internetUsers: 72000000,
    ecommerceSpendUSD: 24000000000,
    rpmRangeLow: 4.5,
    rpmRangeHigh: 16.0,
    affiliateStrength: 7.2,
    languageFit: 'Turkish',
    potentialScore: 76.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'PL',
    name: 'Poland',
    flag: '🇵🇱',
    internetUsers: 34000000,
    ecommerceSpendUSD: 28000000000,
    rpmRangeLow: 8.0,
    rpmRangeHigh: 26.0,
    affiliateStrength: 7.8,
    languageFit: 'Polish / Growing English',
    potentialScore: 80.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'TH',
    name: 'Thailand',
    flag: '🇹🇭',
    internetUsers: 59000000,
    ecommerceSpendUSD: 22000000000,
    rpmRangeLow: 5.0,
    rpmRangeHigh: 17.0,
    affiliateStrength: 7.3,
    languageFit: 'Thai (Strict Localization)',
    potentialScore: 77.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'VN',
    name: 'Vietnam',
    flag: '🇻🇳',
    internetUsers: 78000000,
    ecommerceSpendUSD: 18000000000,
    rpmRangeLow: 4.0,
    rpmRangeHigh: 14.0,
    affiliateStrength: 7.5,
    languageFit: 'Vietnamese',
    potentialScore: 76.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'PH',
    name: 'Philippines',
    flag: '🇵🇭',
    internetUsers: 85000000,
    ecommerceSpendUSD: 16000000000,
    rpmRangeLow: 5.5,
    rpmRangeHigh: 18.0,
    affiliateStrength: 7.6,
    languageFit: 'English / Tagalog Fluent',
    potentialScore: 79.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'QA',
    name: 'Qatar',
    flag: '🇶🇦',
    internetUsers: 2800000,
    ecommerceSpendUSD: 5000000000,
    rpmRangeLow: 15.0,
    rpmRangeHigh: 45.0,
    affiliateStrength: 8.0,
    languageFit: 'Arabic / English High Purchasing',
    potentialScore: 84.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'KW',
    name: 'Kuwait',
    flag: '🇰🇼',
    internetUsers: 4200000,
    ecommerceSpendUSD: 6500000000,
    rpmRangeLow: 14.0,
    rpmRangeHigh: 42.0,
    affiliateStrength: 7.9,
    languageFit: 'Arabic / English',
    potentialScore: 83.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'IL',
    name: 'Israel',
    flag: '🇮🇱',
    internetUsers: 8900000,
    ecommerceSpendUSD: 11000000000,
    rpmRangeLow: 16.0,
    rpmRangeHigh: 46.0,
    affiliateStrength: 8.3,
    languageFit: 'Hebrew / High English',
    potentialScore: 85.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'CZ',
    name: 'Czech Republic',
    flag: '🇨🇿',
    internetUsers: 9400000,
    ecommerceSpendUSD: 10500000000,
    rpmRangeLow: 9.0,
    rpmRangeHigh: 28.0,
    affiliateStrength: 7.6,
    languageFit: 'Czech',
    potentialScore: 79.0,
    tier: 'high-potential'
  },
  {
    countryCode: 'PT',
    name: 'Portugal',
    flag: '🇵🇹',
    internetUsers: 8800000,
    ecommerceSpendUSD: 9500000000,
    rpmRangeLow: 9.5,
    rpmRangeHigh: 28.0,
    affiliateStrength: 7.5,
    languageFit: 'Portuguese / Strong English',
    potentialScore: 78.5,
    tier: 'high-potential'
  },
  {
    countryCode: 'CL',
    name: 'Chile',
    flag: '🇨🇱',
    internetUsers: 17500000,
    ecommerceSpendUSD: 11000000000,
    rpmRangeLow: 7.0,
    rpmRangeHigh: 22.0,
    affiliateStrength: 7.3,
    languageFit: 'Spanish (High Income LatAm)',
    potentialScore: 78.0,
    tier: 'high-potential'
  },

  // --- EMERGING MARKETS (Massive Volume, Fast Digitalization, Blue Ocean Local Arbitrage) ---
  {
    countryCode: 'PK',
    name: 'Pakistan',
    flag: '🇵🇰',
    internetUsers: 110000000,
    ecommerceSpendUSD: 7500000000,
    rpmRangeLow: 1.8,
    rpmRangeHigh: 6.5,
    affiliateStrength: 6.8,
    languageFit: 'Urdu / English Bilingual',
    potentialScore: 75.0,
    tier: 'emerging'
  },
  {
    countryCode: 'IN',
    name: 'India',
    flag: '🇮🇳',
    internetUsers: 750000000,
    ecommerceSpendUSD: 95000000000,
    rpmRangeLow: 2.2,
    rpmRangeHigh: 8.5,
    affiliateStrength: 8.2,
    languageFit: 'Hindi / English High Scale',
    potentialScore: 82.5,
    tier: 'emerging'
  },
  {
    countryCode: 'BD',
    name: 'Bangladesh',
    flag: '🇧🇩',
    internetUsers: 82000000,
    ecommerceSpendUSD: 3800000000,
    rpmRangeLow: 1.5,
    rpmRangeHigh: 5.2,
    affiliateStrength: 6.2,
    languageFit: 'Bengali / English Growing',
    potentialScore: 70.5,
    tier: 'emerging'
  },
  {
    countryCode: 'EG',
    name: 'Egypt',
    flag: '🇪🇬',
    internetUsers: 75000000,
    ecommerceSpendUSD: 6000000000,
    rpmRangeLow: 2.0,
    rpmRangeHigh: 7.0,
    affiliateStrength: 6.5,
    languageFit: 'Arabic (MENA Cultural Hub)',
    potentialScore: 73.0,
    tier: 'emerging'
  },
  {
    countryCode: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    internetUsers: 108000000,
    ecommerceSpendUSD: 9000000000,
    rpmRangeLow: 2.5,
    rpmRangeHigh: 8.0,
    affiliateStrength: 6.9,
    languageFit: 'English (Official / Broad)',
    potentialScore: 74.0,
    tier: 'emerging'
  },
  {
    countryCode: 'OM',
    name: 'Oman',
    flag: '🇴🇲',
    internetUsers: 4500000,
    ecommerceSpendUSD: 3200000000,
    rpmRangeLow: 10.0,
    rpmRangeHigh: 30.0,
    affiliateStrength: 7.1,
    languageFit: 'Arabic / English',
    potentialScore: 76.0,
    tier: 'emerging'
  },
  {
    countryCode: 'BH',
    name: 'Bahrain',
    flag: '🇧🇭',
    internetUsers: 1700000,
    ecommerceSpendUSD: 2100000000,
    rpmRangeLow: 11.0,
    rpmRangeHigh: 32.0,
    affiliateStrength: 7.2,
    languageFit: 'Arabic / English',
    potentialScore: 77.0,
    tier: 'emerging'
  },
  {
    countryCode: 'GR',
    name: 'Greece',
    flag: '🇬🇷',
    internetUsers: 8400000,
    ecommerceSpendUSD: 6800000000,
    rpmRangeLow: 6.5,
    rpmRangeHigh: 20.0,
    affiliateStrength: 6.8,
    languageFit: 'Greek / Moderate English',
    potentialScore: 72.5,
    tier: 'emerging'
  },
  {
    countryCode: 'HU',
    name: 'Hungary',
    flag: '🇭🇺',
    internetUsers: 8600000,
    ecommerceSpendUSD: 5900000000,
    rpmRangeLow: 6.0,
    rpmRangeHigh: 19.0,
    affiliateStrength: 6.7,
    languageFit: 'Hungarian',
    potentialScore: 72.0,
    tier: 'emerging'
  },
  {
    countryCode: 'RO',
    name: 'Romania',
    flag: '🇷🇴',
    internetUsers: 16500000,
    ecommerceSpendUSD: 8500000000,
    rpmRangeLow: 5.5,
    rpmRangeHigh: 17.5,
    affiliateStrength: 6.9,
    languageFit: 'Romanian / High Tech English',
    potentialScore: 74.0,
    tier: 'emerging'
  },
  {
    countryCode: 'AR',
    name: 'Argentina',
    flag: '🇦🇷',
    internetUsers: 39000000,
    ecommerceSpendUSD: 14000000000,
    rpmRangeLow: 3.5,
    rpmRangeHigh: 12.0,
    affiliateStrength: 6.8,
    languageFit: 'Spanish (Rioplatense)',
    potentialScore: 71.5,
    tier: 'emerging'
  },
  {
    countryCode: 'CO',
    name: 'Colombia',
    flag: '🇨🇴',
    internetUsers: 36000000,
    ecommerceSpendUSD: 10500000000,
    rpmRangeLow: 3.8,
    rpmRangeHigh: 13.0,
    affiliateStrength: 6.9,
    languageFit: 'Spanish (High Engagement)',
    potentialScore: 73.0,
    tier: 'emerging'
  }
];
